server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: course-route
          uri: lb://course-service
          predicates:
            - Path=/courses/**
          filters:
            - StripPrefix=1

        - id: registration-route
          uri: lb://registration-service
          predicates:
            - Path=/registrations/**
          filters:
            - StripPrefix=1

        - id: attendance-route
          uri: lb://attendance-service
          predicates:
            - Path=/attendance/**
          filters:
            - StripPrefix=1

        - id: certification-route
          uri: lb://certification-service
          predicates:
            - Path=/certificates/**
          filters:
            - StripPrefix=1

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info,prometheus
  endpoint:
    health:
      show-details: always

---
spring:
  config
