server:
  port: 9003

spring:
  application:
    name: attendance-service

  datasource:
    url: jdbc:mysql://localhost:3306/attendance_service?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

app:
  exchanges:
    registration: registration.events
    attendance: attendance.events
  queues:
    registrationCreated: q.registration.created
  routing:
    registrationCreated: registration.created
