server:
  port: 19020

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: course-service
            uri: http://localhost:9001
            predicates:
              - Path=/courses/**
          - id: registration-service
            uri: http://localhost:9002
            predicates:
              - Path=/registrations/**
          - id: attendance-service
            uri: http://localhost:9003
            predicates:
              - Path=/attendance/**
          - id: certification-service
            uri: http://localhost:9004
            predicates:
              - Path=/certificates/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
